name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.11"]

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    # Step 4: Run tests
    - name: Run pytest
      run: pytest tests

    # Step 5: Final CI Status (single report step)
    - name: Report CI Status
      if: always()
      run: |
        echo "=============================="
        echo " CI finished with status: ${{ job.status }}"
        echo " Python version: ${{ matrix.python-version }}"
        echo "=============================="
