name: CI

on:
  push:
    branches: [ "master" ]   # Run workflow on every push to master
  pull_request:
    branches: [ "master" ]   # Also run on pull requests targeting master

jobs:
  build:
    runs-on: ubuntu-latest   # GitHub runner environment

    strategy:
      matrix:                # Matrix = run in parallel with different versions
        python-version: [3.9, 3.10, 3.11]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: pytest tests

    - name: Notify result
      if: always()   # Always run this step, even if build fails
      run: echo "Build finished with status ${{ job.status }}"

