name: CI

on:
  push:
    branches: [ "master" ]  
  pull_request:
    branches: [ "master" ]   

jobs:
  build:
    runs-on: ubuntu-latest   

    strategy:
      matrix:
        python-version: ["3.9", "3.11"]   

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests
        run: pytest tests

      - name: Notify result 1
        if: always()   
        run: echo "Build finished with status ${{ job.status }}"

      - name: Notify result 2  
        if: always()
        run: echo "Build finished with status ${{ job.status }}"

      - name: Run tests again
        run: pytest

      - name: Final CI Status 
        if: always() 
        run: echo "Final CI Status ${{ job.status }}"

      - name: Notify result 3 
        if: always() 
        run: echo "Build finished with status ${{ job.status }}"



        
        
