name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show environment
        run: |
          echo "OS Info:"
          uname -a
          echo "Files in repo:"
          ls -la

      - name: Sanity check
        run: |
          echo "Running CI sanity check"
          test -f readme.txt
          echo "OK"
